-- Sequência para T_FIN_RECEITAS
CREATE SEQUENCE seq_receita
START WITH 1
INCREMENT BY 1;

-- Criação da tabela T_FIN_RECEITAS
CREATE TABLE T_FIN_RECEITAS (
    ID_RECEITA INTEGER NOT NULL PRIMARY KEY,
    NOME_RECEITA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL,
    ID_USER NUMBER NOT NULL -- Adicionando coluna ID_USER
);

-- Sequência para T_FIN_DESPESAS
CREATE SEQUENCE seq_despesa
START WITH 1
INCREMENT BY 1;

-- Criação da tabela T_FIN_DESPESAS
CREATE TABLE T_FIN_DESPESAS (
    ID_DESPESA INTEGER NOT NULL PRIMARY KEY,
    NOME_DESPESA VARCHAR2(100) NOT NULL,
    VALOR NUMBER(10,2) NOT NULL,
    DESCRICAO VARCHAR2(255),
    DATA_INCLUSAO DATE NOT NULL,
    ID_USER NUMBER NOT NULL -- Adicionando coluna ID_USER
);

-- Criação da tabela T_FIN_USER
CREATE TABLE T_FIN_USER (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOME_COMPLETO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) NOT NULL UNIQUE,
    IDADE_NASC DATE NOT NULL,
    DATA_CRIACAO DATE DEFAULT SYSDATE,
    SENHA VARCHAR2(255) NOT NULL
);

-- Chave estrangeira para T_FIN_DESPESAS
ALTER TABLE T_FIN_DESPESAS
ADD CONSTRAINT FK_DESPESA_USER
FOREIGN KEY (ID_USER)
REFERENCES T_FIN_USER(ID_USUARIO);

-- Chave estrangeira para T_FIN_RECEITAS
ALTER TABLE T_FIN_RECEITAS
ADD CONSTRAINT FK_RECEITA_USER
FOREIGN KEY (ID_USER)
REFERENCES T_FIN_USER(ID_USUARIO);

select *from T_FIN_DESPESAS;
